### ISSUE TITLE
Cannot dismiss the first login screen after selecting my google Account

### ISSUE THREAD

**Issue by TheBlueHawk** [CoronaTeam/CoronaGame#150]

**Comment by Ulydev** [comment]
What are the steps to reproduce? What's the expected behaviour?

**Comment by TheBlueHawk** [comment]
After the intro screens, I sign up with a google account but I'm not redirected to the tabView as expected, instead I still see the login screen

**Comment by TheBlueHawk** [comment]
The error occurs both on the emulator and a physical device. Here is the error showing up in the log:
W/authenticationActivity: signInResult:failed code=12500

**Comment by Ulydev** [comment]
https://github.com/firebase/firebase-android-sdk/issues/664

**Comment by TheBlueHawk** [comment]
Thank you, now the login works as expected!
